baseURL: https://aman-sharma-am01portfolio.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Learn More
    subtitle: "HELLO, MY NAME IS AMAN. WELCOME TO MY PORTFOLIO WEBSITE!"
    title: Hello, my name is Aman.
  blog: {}
  contact:
    address:
      - city: LBS
        country: United Kingdom
        street: Nw1 4SA
        title: Address
    buttonClear: Start Again
    buttonSend: Say Hello
    email:
      - email: aman.sharma@a.com
        title: Email
    enable: yes
    phone:
      - phone: (0791) 234567
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Aman Akshay Sharma 2021
    enable: yes
    quicklinks:
      - alt: this cool guy
        text: 'I learnt how to use R from '
        url: https://www.linkedin.com/in/kostis-christodoulou-285147/
    social:
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/AmanSharmaGitHub
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/amanakshaysharma
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: All Posts
        url: blogs
      - name: About Me
        url: blogs/pageone
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Portfolio Website
    title: Aman
  tiles:
    enable: yes
    showcase:
      - image: Aman.jpg
        subtitle: Who am I?
        title: About Me
        url: blogs/pageone
      - image: hansrosling.jpeg
        subtitle: Global Living Standards
        title: Gapminder Analysis
        url: blogs/pagetwo
      - image: NYSE.jpeg
        subtitle: It only goes up?
        title: Financial Analysis
        url: blogs/pagethree
      - image: GSS.png
        subtitle: Human Connection
        title: Social Media Analysis
        url: blogs/pagefour
      - image: banner.png
        subtitle: Contact Me
        title: Get in touch
        url: blogs/pagefive

  two:
    buttonText: R Analysis
    enable: yes
    subtitle: "Welcome to my portfolio website. Here you can find some work I have done on R while studying at London Business School."
    title: Welcome!
    url: blogs
